version: 2
jobs:
  build:
    working_directory: ~/json2java
    docker:
      - image: openjdk:8
    steps:
      - run: apt-get -qq update; apt-get -y install git
      - type: checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew --version
      - run: ./gradlew assemble --full-stacktrace
      - run: ./gradlew test --full-stacktrace
      - type: test-results-store
        path: core/build/test-results/
      - type: test-results-store
        path: idea/build/test-results/
