version: 2
jobs:
  build:
    working_directory: ~/json2java
    docker:
      - image: openjdk:8
    steps:
      - type: shell
        name: Set up the build environment
        command: apt-get -qq update; apt-get -y install git
      - type: checkout
      - type: shell
        name: Set up the Gradle build
        command: chmod +x ./gradlew; ./gradlew --version
      - type: shell
        name: Assemble the outputs of this project
        command: ./gradlew :core:build --full-stacktrace; ./gradlew :idea:buildPlugin --full-stacktrace
      - type: shell
        name: Set up code coverage reporter for Codacy
        command: curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > jpm4j.jar; java -jar jpm4j.jar -u init; ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
      - type: shell
        name: Run all checks including unit test and static code analysis
        command: ./gradlew check --full-stacktrace
      - type: shell
        name: Upload code coverage for core module
        command: ~/jpm/bin/codacy-coverage-reporter -l Java -r core/build/reports/jacoco/test/jacocoTestReport.xml
      - type: shell
        name: Upload code coverage for idea module
        command: ~/jpm/bin/codacy-coverage-reporter -l Java -r idea/build/reports/jacoco/test/jacocoTestReport.xml
      - type: test-results-store
        path: core/build/test-results/
      - type: test-results-store
        path: idea/build/test-results/
      - type: artifacts-store
        path: core/build/reports/jacoco/test
        destination: core/jacoco
      - type: artifacts-store
        path: idea/build/reports/jacoco/test
        destination: idea/jacoco
      - type: artifacts-store
        path: idea/build/distributions
        destination: idea
